CREATE TABLE IF NOT EXISTS `IT202-S24-ProductDetails` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `asin` VARCHAR(100) NOT NULL,
    `product_title` VARCHAR(100) NOT NULL,
    `product_price` DECIMAL(10, 2) NOT NULL,
    `product_original_price` DECIMAL(10, 2),
    `currency` VARCHAR(10) NOT NULL,
    `country` VARCHAR(10) NOT NULL,
    `product_star_rating` DECIMAL(3, 1) NOT NULL,
    `product_num_ratings` INT NOT NULL,
    `product_url` TEXT NOT NULL,
    `product_photo` TEXT NOT NULL,
    `product_num_offers` INT,
    `product_availability` VARCHAR(50),
    `is_best_seller` BOOLEAN NOT NULL,
    `is_amazon_choice` BOOLEAN NOT NULL,
    `climate_pledge_friendly` BOOLEAN NOT NULL,
    `sales_volume` VARCHAR(50),
    `about_product` TEXT,
    `product_description` TEXT,
    `product_information` TEXT,
    `rating_distribution` TEXT,
    `product_photos` TEXT,
    `product_details` TEXT,
    `customers_say` TEXT,
    `review_aspects` TEXT,
    `category_path` TEXT,
    `product_variations` TEXT,
    `is_prime` BOOLEAN NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE(`asin`, `product_url`(255))
);